"""Command-line entry point for chatting with a local notebook RAG index."""

from __future__ import annotations

import argparse
import os
import sys
from collections.abc import Sequence

from nbrag.ollama import (
    DEFAULT_CHAT_MODEL,
    DEFAULT_OLLAMA_HOST,
    DEFAULT_TIMEOUT_SECONDS,
    OllamaChatClient,
    OllamaEmbeddingProvider,
    OllamaError,
)
from nbrag.rag import (
    DEFAULT_CONTEXT_CHAR_LIMIT,
    LocalVectorIndex,
    RagAnswer,
    answer_question,
    read_index,
)


def main(argv: Sequence[str] | None = None) -> int:
    """Chat with a local vector index using Ollama."""

    args = _parse_args(argv)
    index = read_index(args.index)
    embed_model = args.embed_model or os.environ.get("OLLAMA_EMBED_MODEL") or index.embedding_model
    embedder = OllamaEmbeddingProvider(
        model=embed_model,
        host=args.ollama_host,
        timeout_seconds=args.timeout,
    )
    chat_client = OllamaChatClient(
        model=args.chat_model,
        host=args.ollama_host,
        timeout_seconds=args.timeout,
    )

    if args.question:
        try:
            _print_answer(
                _answer(args.question, args, index, embedder, chat_client),
                show_context=args.show_context,
                show_metrics=args.show_metrics,
            )
        except OllamaError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            return 1
        return 0

    print("nbrag chat. Ask about the indexed notebooks, or type 'exit'/'quit' to stop.")
    while True:
        try:
            question = input("nbrag> ").strip()
        except EOFError:
            print()
            return 0
        if not question:
            continue
        if question.lower() in {"exit", "quit"}:
            return 0
        try:
            _print_answer(
                _answer(question, args, index, embedder, chat_client),
                show_context=args.show_context,
                show_metrics=args.show_metrics,
            )
        except OllamaError as exc:
            print(f"Error: {exc}", file=sys.stderr)


def _answer(
    question: str,
    args: argparse.Namespace,
    index: LocalVectorIndex,
    embedder: OllamaEmbeddingProvider,
    chat_client: OllamaChatClient,
) -> RagAnswer:
    return answer_question(
        index,
        question,
        embedder=embedder,
        chat_client=chat_client,
        top_k=args.top_k,
        context_char_limit=args.context_chars,
    )


def _print_answer(
    answer: RagAnswer,
    *,
    show_context: bool,
    show_metrics: bool,
) -> None:
    print()
    print(answer.answer)
    print()
    if show_metrics and answer.metrics is not None:
        metrics = answer.metrics
        print(
            f"Timing (ms): retrieve={metrics.retrieve_ms:.1f} "
            f"generate={metrics.generate_ms:.1f} total={metrics.total_ms:.1f}"
        )
        if metrics.embed_usage is not None and metrics.embed_usage.prompt_tokens is not None:
            print(f"Embed tokens (prompt): {metrics.embed_usage.prompt_tokens}")
        if metrics.chat_usage is not None:
            chat = metrics.chat_usage
            if chat.prompt_tokens is not None or chat.completion_tokens is not None:
                print(
                    f"Chat tokens: prompt={chat.prompt_tokens} completion={chat.completion_tokens}"
                )
        print(f"Context chars: {metrics.context_chars}")
        print()
    print("Sources:")
    for result in answer.results:
        cells = ", ".join(str(index) for index in result.chunk.cell_indices) or "unknown"
        print(
            f"- {result.chunk.notebook_id} cells {cells} "
            f"(rank {result.rank}, score {result.score:.4f})"
        )
        if show_context:
            print(result.chunk.text.strip())
            print()
    print()


def _parse_args(argv: Sequence[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="nbrag-chat",
        description="Ask questions against a local Ollama-backed notebook RAG index.",
    )
    parser.add_argument("index", help="Path to an index JSON generated by nbrag-embed.")
    parser.add_argument(
        "--question",
        help="Ask one question and exit. Omit for an interactive prompt.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=4,
        help="Number of retrieved chunks to send to the chat model. Default: 4.",
    )
    parser.add_argument(
        "--context-chars",
        type=int,
        default=DEFAULT_CONTEXT_CHAR_LIMIT,
        help=f"Maximum retrieved context characters. Default: {DEFAULT_CONTEXT_CHAR_LIMIT}.",
    )
    parser.add_argument(
        "--embed-model",
        default=None,
        help=(
            "Ollama embedding model for questions. Default: OLLAMA_EMBED_MODEL, "
            "then the model recorded in the index."
        ),
    )
    parser.add_argument(
        "--chat-model",
        default=None,
        help=f"Ollama chat model. Default: {DEFAULT_CHAT_MODEL}.",
    )
    parser.add_argument(
        "--ollama-host",
        default=None,
        help=f"Ollama base URL. Default: OLLAMA_HOST or {DEFAULT_OLLAMA_HOST}.",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=DEFAULT_TIMEOUT_SECONDS,
        help=f"Ollama request timeout in seconds. Default: {DEFAULT_TIMEOUT_SECONDS:g}.",
    )
    parser.add_argument(
        "--show-context",
        action="store_true",
        help="Print retrieved chunk text under each source.",
    )
    parser.add_argument(
        "--show-metrics",
        action="store_true",
        help="Print timing and token usage after each answer.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    raise SystemExit(main())
